package com.hospital.workstation;

import java.time.LocalDate;

/** 病案首页保存参数：患者长期资料和本次住院归档资料一次提交。 */
public record CaseHomeRequest(
        String idType,
        String idCardNo,
        String nationality,
        String ethnicity,
        String occupation,
        String maritalStatus,
        String nativePlaceProvince,
        String nativePlaceCity,
        String birthPlaceProvince,
        String birthPlaceCity,
        String birthPlaceCounty,
        String birthPlaceDetail,
        String currentAddressProvince,
        String currentAddressCity,
        String currentAddressCounty,
        String currentAddressDetail,
        String postalCode,
        String phone,
        String registeredAddressProvince,
        String registeredAddressCity,
        String registeredAddressCounty,
        String registeredAddressDetail,
        String registeredPostalCode,
        String employerName,
        String employerAddress,
        String employerPhone,
        String employerPostalCode,
        String emergencyContactName,
        String emergencyContactRelation,
        String emergencyContactAddress,
        String emergencyContactPhone,
        String aboBloodType,
        String rhBloodType,
        String feeType,
        String insuranceType,
        String admissionSource,
        Integer admissionCount,
        Long dischargeDepartmentId,
        String dischargeBedNo,
        String dischargeMethod,
        Boolean readmissionWithin31Days,
        Boolean interhospitalOperation,
        Long departmentDirectorId,
        Long chiefPhysicianId,
        Long medicalGroupLeaderId,
        Long residentDoctorId,
        Long headNurseId,
        Long responsibleNurseId,
        Long qualityDoctorId,
        Long qualityNurseId,
        LocalDate qualityControlDate,
        Integer specialNursingDays,
        Integer levelOneNursingDays,
        Integer levelTwoNursingDays,
        Integer levelThreeNursingDays) {
}
