-- 病案首页补充：患者长期人口学资料与单次住院归档资料分开保存。
ALTER TABLE patient
    ADD COLUMN native_place_province VARCHAR(64) NULL AFTER birth_place,
    ADD COLUMN native_place_city VARCHAR(64) NULL AFTER native_place_province,
    ADD COLUMN birth_place_province VARCHAR(64) NULL AFTER native_place_city,
    ADD COLUMN birth_place_city VARCHAR(64) NULL AFTER birth_place_province,
    ADD COLUMN birth_place_county VARCHAR(64) NULL AFTER birth_place_city,
    ADD COLUMN birth_place_detail VARCHAR(255) NULL AFTER birth_place_county,
    ADD COLUMN current_address_province VARCHAR(64) NULL AFTER current_address,
    ADD COLUMN current_address_city VARCHAR(64) NULL AFTER current_address_province,
    ADD COLUMN current_address_county VARCHAR(64) NULL AFTER current_address_city,
    ADD COLUMN current_address_detail VARCHAR(255) NULL AFTER current_address_county,
    ADD COLUMN registered_address_province VARCHAR(64) NULL AFTER registered_address,
    ADD COLUMN registered_address_city VARCHAR(64) NULL AFTER registered_address_province,
    ADD COLUMN registered_address_county VARCHAR(64) NULL AFTER registered_address_city,
    ADD COLUMN registered_address_detail VARCHAR(255) NULL AFTER registered_address_county,
    ADD COLUMN registered_postal_code VARCHAR(16) NULL AFTER postal_code,
    ADD COLUMN employer_name VARCHAR(128) NULL AFTER registered_postal_code,
    ADD COLUMN employer_address VARCHAR(255) NULL AFTER employer_name,
    ADD COLUMN employer_phone VARCHAR(32) NULL AFTER employer_address,
    ADD COLUMN employer_postal_code VARCHAR(16) NULL AFTER employer_phone,
    ADD COLUMN emergency_contact_address VARCHAR(255) NULL AFTER emergency_contact_relation,
    ADD COLUMN abo_blood_type VARCHAR(4) NULL AFTER emergency_contact_phone,
    ADD COLUMN rh_blood_type VARCHAR(8) NULL AFTER abo_blood_type;

CREATE TABLE case_home_page (
    admission_id INT UNSIGNED PRIMARY KEY,
    admission_count INT UNSIGNED NOT NULL DEFAULT 1,
    discharge_department_id INT UNSIGNED NULL,
    discharge_bed_no VARCHAR(32) NULL,
    discharge_method VARCHAR(32) NULL,
    readmission_within_31_days BOOLEAN NULL,
    interhospital_operation BOOLEAN NULL,
    department_director_id INT UNSIGNED NULL,
    chief_physician_id INT UNSIGNED NULL,
    medical_group_leader_id INT UNSIGNED NULL,
    resident_doctor_id INT UNSIGNED NULL,
    head_nurse_id INT UNSIGNED NULL,
    responsible_nurse_id INT UNSIGNED NULL,
    quality_doctor_id INT UNSIGNED NULL,
    quality_nurse_id INT UNSIGNED NULL,
    quality_control_date DATE NULL,
    special_nursing_days INT UNSIGNED NOT NULL DEFAULT 0,
    level_one_nursing_days INT UNSIGNED NOT NULL DEFAULT 0,
    level_two_nursing_days INT UNSIGNED NOT NULL DEFAULT 0,
    level_three_nursing_days INT UNSIGNED NOT NULL DEFAULT 0,
    updated_by INT UNSIGNED NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_case_home_admission FOREIGN KEY (admission_id) REFERENCES admission(admission_id),
    CONSTRAINT fk_case_home_discharge_department FOREIGN KEY (discharge_department_id) REFERENCES department(department_id),
    CONSTRAINT fk_case_home_director FOREIGN KEY (department_director_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_chief FOREIGN KEY (chief_physician_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_group_leader FOREIGN KEY (medical_group_leader_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_resident FOREIGN KEY (resident_doctor_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_head_nurse FOREIGN KEY (head_nurse_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_responsible_nurse FOREIGN KEY (responsible_nurse_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_quality_doctor FOREIGN KEY (quality_doctor_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_quality_nurse FOREIGN KEY (quality_nurse_id) REFERENCES system_user(user_id),
    CONSTRAINT fk_case_home_updater FOREIGN KEY (updated_by) REFERENCES system_user(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
